apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-nose-tests
spec:
  steps:
    - name: run-tests
      image: python:3.8
      script: |
        #!/bin/sh
        echo "Installing dependencies..."
        pip install nose
        echo "Running tests..."
        nosetests tests/
