apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine:latest
      script: |
        #!/bin/sh
        echo "Cleaning up resources..."
        rm -rf /workspace/output
        echo "Cleanup completed!"
